Tasks/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'Tasks'
urlpatterns = [
    path('', views.tasklist, name='todo'),
    path('create/', views.createTask, name='create'),
    path('details/<str:pk>/', views.detailTask, name='details'),
    path('update_list/<str:pk>/', views.updateTask, name='update'),
    path('delete_item/<str:pk>/', views.deleteTask, name='delete'),
    path('delete_all/', views.clearlTasks, name='deleteall'),
]

kelo_todoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Tasks.urls')),
    path('users/', include('myusers.urls')),
]

myusers/urls.py
from re import template
from django.contrib import admin
from django.urls import path
from myusers import views
from django.contrib.auth import views as auth_views
from myusers import forms

urlpatterns = [
    path('signup/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='myusers/login.html'), name='login'),
     path('logout/', auth_views.LogoutView.as_view(template_name='myusers/logout.html'), name='logout'),
    
]

Tasks/models.py
from turtle import title
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class TasksList(models.Model):
    tags = [
    ('New', 'New'),
    ('Running', 'Running'),
    ('Completed', 'Completed'),
]
    user = models.ForeignKey(User, on_delete=models.CASCADE ,blank=True, null=True)
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=200)
    rand_tags = models.CharField(max_length=15, choices=tags, default='New')
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['complete']
    

class History(models.Model):
    
    tags = [
    ('danger', 'New'),
    ('warning', 'Running'),
    ('success', 'Completed'),
]
    user = models.ForeignKey(User, on_delete=models.CASCADE ,blank=True, null=True)
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=200)
    rand_tags = models.CharField(max_length=15, choices=tags, default='danger')
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['complete']

myusers/models.py
from django.db import models

# Create your models here.

Tasks/forms.py
from xml.dom.minidom import Attr
from .models import TasksList
from django.forms import ModelForm, widgets
from django import forms

class TasksListForm(forms.ModelForm):
    class Meta:
        model = TasksList
        fields = [ 'title', 'description','rand_tags', 'complete',]

        widgets = {
            #'rand_tags':forms.ChoiceField(),
            
        }
    def __init__(self, *args, **kwargs):
        super(TasksListForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            if name == 'complete' or field =='complete':
                continue    
            field.widget.attrs.update({'class':'form-control','placeholder':name})

myusers/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class usersform(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1','password2']
        
        
    def __init__(self, *args, **kwargs):
        super(usersform, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            if name == 'complete' or field =='complete':
                continue    
            field.widget.attrs.update({'class':'form-control','placeholder':name})
            
            

            

Tasks/views.py
from multiprocessing import context
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import TasksList, History
from .forms import TasksListForm
from django.contrib import messages
import random

# Create your views here.

def tasklist(request):
    profile = request.user
    if request.user.is_authenticated:
        taskul = TasksList.objects.all().filter(user = profile)
    else:
        taskul = History.objects.all()
    colors = ['danger','info', 'success','primary', 'secondary','warning']
    mycolor = random.choice(colors)
    context = {'taskul':taskul,'mycolor':mycolor, 'profile':profile}
    return render(request, 'Tasks/index.html', context)

@login_required(login_url="login") 
def createTask(request):
    form = TasksListForm()
    profile = request.user
    if request.method == "POST":
        form = TasksListForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.user = profile
            messages.success(request, f'Task was sucessfully created')
            project.save()
            
        return redirect('Tasks:todo')
    context = {'form':form}
    return render(request, 'Tasks/create.html', context)



@login_required(login_url="login") 
def detailTask(request, pk):
    profile = request.user
    if profile.is_authenticated:
        taskul = TasksList.objects.all().filter(user = profile).get(id=pk)
    context = {'taskul':taskul}
    return render(request, 'Tasks/detail.html', context)


@login_required(login_url="login") 
def updateTask(request, pk):
    taskupdate = TasksList.objects.get(id=pk)
    form = TasksListForm(instance = taskupdate)
    
    if request.method == "POST":
        form = TasksListForm(request.POST, instance = taskupdate)
        if form.is_valid():
            messages.success(request, f'Task was sucessfully Updated')
            form.save()
            
        return redirect('Tasks:todo')
    context = {'form':form}
    return render(request, 'Tasks/create.html', context)


@login_required(login_url="login") 
def deleteTask(request, pk):
    deleteitem = TasksList.objects.get(id=pk)
    if request.method == "POST":
        deleteitem.delete()
        return redirect('Tasks:todo')
    
    context = {'deleteitem':deleteitem}
    return render(request, 'Tasks/delete.html', context)


@login_required(login_url="login") 
def clearlTasks(request):
    profile = request.user
    items = TasksList.objects.all().filter(user = profile)
    if request.method == "POST":
        items.delete()
        return redirect('Tasks:todo')
    context = {'items':items}
    return render(request, 'Tasks/clear.html', context)

myusers/views.py
from email import message
from django.shortcuts import render, redirect
from myusers.forms import usersform
from django.contrib import messages


# Create your views here.
def register(request):
    form = usersform()
    if request.method == "POST":
        form = usersform(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, account was sucessfully created')
            return redirect('login')
    else:
        form = usersform()
    context = {'form':form}
    return render(request, 'myusers/register.html', context)

Tasks/templates/Tasks/clear.html
{% extends 'Tasks/index.html' %}
{% load static %}

{% block content %}
<div class="alert alert-danger" role="alert">
    <h3 class='text-light'>You wanna delete all items ?</h3>
    {% for item in items %}
    <div class='p-1 bg-white'><h4>{{item.title}}</h4></div>
    {% endfor %}
    <form method='POST'>
        {% csrf_token %}
        
        <a class='btn btn-secondary' href='{% url "Tasks:todo" %}'>Go back</a>
        <button class='btn-danger btn' type='submit'>Delete all</button>
        
    </form>
  </div>

{% endblock content %}

Tasks/templates/Tasks/create.html
{% extends 'Tasks/index.html' %}
{% load static %}
{% block content %}
<form class="form-signin" method="POST">
     {% csrf_token %}
     <div class="text-center mb-4">
       <h1 class="h3 mb-3 font-weight-normal">Add Task</h1>
     </div>
   {% for field in form %}
     {% if field == form.title or field == form.complete %}
     <label for="{{field.label}}">{{field.label}}</label>
     <div class="form-label-group">
       {{field}}
     </div>
     {% else %}
     <div class="form-label-group">
       {{field}}
     </div>
     {% endif %}
     {% endfor %}
     <p class='text-decoration-underline text-muted'>Tick 'complete' and select Completed from the options to End a Task</p>
     
     <button class="btn btn-lg btn-primary btn-block" type="submit">Add</button>
</form>

{% endblock content %}

Tasks/templates/Tasks/delete.html
{% extends 'Tasks/index.html' %}
{% load static %}

{% block content %}
<div class="alert alert-danger" role="alert">
    <form method='POST'>
        {% csrf_token %}
        <h3>You wanna delete {{deleteitem}}</h3>
        <a class='btn btn-secondary' href='{% url "Tasks:todo" %}'>Go back</a>
        <button class='btn-success btn' type='submit'>Delete</button>
        
    </form>
  </div>

{% endblock content %}

Tasks/templates/Tasks/detail.html
{% extends 'Tasks/index.html' %}
{% load static %}
{% block content %}

<div class="container mt-3">
    <header style='border-bottom: 3px solid white' class="blog-header border-white border-2 bg-dark  py-3">
      <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            <a href='{% url "Tasks:todo" %}' type="button" class="btn btn-outline-primary mx-2 ">&#8678 Back</a>
        </div>
        <div class="col-4 text-center">
          <h3 class="blog-header-logo text-light" href="#">Task detail</h3>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
          
        <a class="btn btn-sm btn-outline-secondary mx-2" href="#">{{taskul.created}}</a>
        </div>
      </div>
    </header>
  
  
    <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
      <div class="col-md-6 px-0">
        <a><span class="badge bg-primary badge-primary">Title</span></a>
        <h1 class="display-5 ">{{taskul.title}}</h1>
        
        <div style='border: 1px solid red' class=' border-2 border-danger p-3'>
            <a><span class="badge bg-danger badge-danger">Content</span></a>
            <p class="lead my-3">{{taskul.description}}</p>
        </div>
      </div>

      <div class="btn-group float-end" role="group" aria-label="Basic example">
        <a href='{% url "Tasks:update" taskul.id %}' type="button" class="btn btn-success">Update</a>
        <a href='{% url "Tasks:delete" taskul.id %}' type="button" class="btn btn-danger ">Delete</a>
      </div>
    </div>
  
    
</div>

{% endblock content%}

Tasks/templates/Tasks/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Kelo Todolist</title>
    <link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet" />
    <link href='{% static "css/font-awesome.min.css" %}' rel="stylesheet" />
    <link href='{% static "css/style.css" %}' rel="stylesheet" />

    <style>
      .gspot input[type=text], .gspot input[type=password]{
        width:100%;
        border-radius: 10px;
      }
    </style>
    
  </head>
  <body  class="snippet-body">
    {% if messages %}
    {% for message in messages%}
    <div class="alert alert-success alert-dismissible fade show {{message.tag}}" role="alert">
      {{message}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}
    <div class="row d-flex justify-content-center container">
      
      <div style='margin-top:80px' class="col-md-8">
        <nav class="navbar navbar-light bg-light">
          {% if user.is_authenticated %}
          <h4 class="navbar-brand text-{{mycolor}} mx-3">Hi, {{request.user}}</h4>
          {% else %}
          <a class="navbar-brand mx-3"></a>
          {% endif %}
          <div class="form-inline">
            {% if user.is_authenticated %}
            <a href='{% url "logout" %}' class="btn btn-outline-success mx-3 my-sm-0" type="button">Logout</a>
            {% else %}
            <a href='{% url "login" %}' class="btn btn-outline-success mx-3 my-sm-0" type="button">Login</a>
            {% endif %}
          </div>
        </nav>
        <div class="card-hover-shadow-2x mb-3 card">
          <div class="card-header-tab card-header">
            <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
               <h4></h4> 
              <i class="fa fa-tasks"></i>&nbsp;Todo List
            </div>
          </div>
          <div class="scroll-area-sm">
            <perfect-scrollbar class="ps-show-limits">
              <div style="position: static" class="ps ps--active-y">
                <div class="ps-content">
                  <ul class="list-group list-group-flush">

                    {% for item in taskul %}
                    <li class="list-group-item">
                      <div class="todo-indicator bg-{{mycolor}}"></div>
                      <div class="widget-content p-0">
                        <div class="widget-content-wrapper">
                          <div class="widget-content-left mr-2">
                            <div class="custom-checkbox custom-control">
                              <input
                                class="custom-control-input"
                                id="exampleCustomCheckbox12"
                                type="checkbox"
                              /><label
                                class="custom-control-label"
                                for="exampleCustomCheckbox12"
                                >&nbsp;</label
                              >
                            </div>
                          </div>
                          <div class="widget-content-left">
                            <div class="widget-heading text-lg-start">
                              {% if item.rand_tags == 'Completed' and item.complete == True %}
                              <h4 class='text-lg-start text-decoration-line-through'>{{item.title}}</h4>
                              {% else %}
                              <h4 class=''>{{item.title}}</>
                              {% endif %}
                              {% if item.rand_tags == 'New' %}
                              <div class="badge bg-danger ml-3">
                              {% elif item.rand_tags == 'Completed' and item.complete == True %}
                              <div class="badge bg-success ml-3 ">
                              {% else %}
                              <div class="badge bg-warning ml-3">
                              {%endif%}
                                {{item.rand_tags}}
                              </div>
                            </div>
                            <div class="widget-subheading"><i>{{item.created}}</i></div>
                          </div>
                          <div class="widget-content-right">
                            <a href='{% url "Tasks:details" item.id %}'
                              class="border-0 btn-transition btn btn-outline-success">
                              <i class="fa fa-check">&#10175</i>
                            </a>
                            <a href='{% url "Tasks:update" item.id %}'
                              class="border-0 btn-transition btn btn-outline-success">
                              <i class="fa fa-check">&#9997</i>
                            </a>
                            <a href='{% url "Tasks:delete" item.id %}'
                              class="border-0 btn-transition btn btn-outline-danger"
                            >
                              <i class="fa fa-trash">&#10060</i>
                            </a>
                          </div>
                        </div>
                      </div>
                    </li>
                    {%endfor %}
                    
                  </ul>
                </div>
              </div>
            </perfect-scrollbar>
          </div>
          <div class="d-block text-right card-footer">
            <a href='{% url "Tasks:deleteall" %}' class="mr-2 btn btn-danger ">Delete All</a>
            <a type='button' href='{% url "Tasks:create" %}' class="btn btn-primary">Add Task</a>
          </div>
        </div>
        
      </div>
      
    </div>
    {% endblock content %}
    <script
      type="text/javascript"
      src="{% static 'js/jquery-1.11.3.min.js' %}"
    ></script>
    <script type="text/javascript" src='{% static "js/bootstrap.bundle.min.js" %}'></script>
  </body>
</html>

myusers/templates/myusers/login.html
{% extends 'Tasks/index.html' %}
{% load static %}
{% block content %}

    <form method='POST' class="form-signin">
        {% csrf_token %}
  <div class="text-center mb-4">
    <h1 class="h3 mb-3 font-weight-normal">Login</h1>
  </div>
{% for field in form %}
  <div class="form-label-group gspot">
    {{field}}
    <label for="{{field.label}}">{{field.label}}</label>
  </div>
{% endfor %}
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
  or 
  <a href='{% url "register" %}' type="button" class="btn btn-link">Register</a>
</form>
{% endblock content %}

myusers/templates/myusers/logout.html
{% extends 'Tasks/index.html' %}
{% load static %}
{% block content %}

<div class="alert alert-secondary" role="alert">
   <h3>You have been logged out</h3>
   <div class="btn-group" role="group" aria-label="Basic example">
    <a href='{% url "Tasks:todo" %}' type="button" class="btn btn-primary">Home</a>
    
    <a href='{% url "login" %}' type="button" class="btn btn-secondary">Login</a>
  </div>
{% endblock content %}

myusers/templates/myusers/register.html
{% extends 'Tasks/index.html' %}
{% load static %}
{% block content %}
    <form method='POST' class="form-signin">
        {% csrf_token %}
  <div class="text-center mb-4">
    <h1 class="h3 mb-3 font-weight-normal">Register</h1>
  </div>
{% for field in form %}
  <div class="form-label-group">
    {{field}}
    <label for="{{field.label}}">{{field.label}}</label>
  </div>
{% endfor %}
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign-Up</button>
  <span uk-icon="icon: check">Or</span>
  <a href='{% url "login" %}' type="button" class="btn btn-link">Login</a>
</form>
{% endblock content %}